name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.name || matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.13" }
          - { python: "3.12" }
          - { python: "3.11" }
          - { python: "3.13", name: Windows, os: windows-latest }
          - { python: "3.13", name: Mac, os: macos-latest }
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv run --locked tox run -e ${{ matrix.tox || matrix.python }}
